// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

var apiBaseUrl = "https://conduit.productionready.io/api";

var articleUrl = "" + (String(apiBaseUrl) + "/articles");

function author(json) {
  return /* record */[
          /* username */Json_decode.field("username", Json_decode.string, json),
          /* bio */Json_decode.optional((function (param) {
                  return Json_decode.field("bio", Json_decode.string, param);
                }), json),
          /* image */Json_decode.field("image", Json_decode.string, json),
          /* following */Json_decode.field("following", Json_decode.bool, json)
        ];
}

function article(json) {
  return /* record */[
          /* slug */Json_decode.field("slug", Json_decode.string, json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* description */Json_decode.field("description", Json_decode.string, json),
          /* body */Json_decode.field("body", Json_decode.string, json),
          /* tagList */Json_decode.field("tagList", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json),
          /* createdAt */Json_decode.field("createdAt", Json_decode.string, json),
          /* updatedAt */Json_decode.field("updatedAt", Json_decode.string, json),
          /* favorited */Json_decode.field("favorited", Json_decode.bool, json),
          /* favoritesCount */Json_decode.field("favoritesCount", Json_decode.$$int, json),
          /* author */Json_decode.field("author", author, json)
        ];
}

function articleList(json) {
  return Json_decode.array(article, json);
}

function articlesResponse(json) {
  return /* record */[
          /* articles */Json_decode.field("articles", articleList, json),
          /* articlesCount */Json_decode.field("articlesCount", Json_decode.$$int, json)
        ];
}

var Decode = /* module */[
  /* author */author,
  /* article */article,
  /* articleList */articleList,
  /* articlesResponse */articlesResponse
];

function fetchArticles(callback) {
  return fetch(articleUrl).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                var articlesResponse$1 = articlesResponse(json);
                Curry._1(callback, articlesResponse$1[/* articles */0]);
                return Promise.resolve(/* () */0);
              }));
}

exports.apiBaseUrl = apiBaseUrl;
exports.articleUrl = articleUrl;
exports.Decode = Decode;
exports.fetchArticles = fetchArticles;
/* articleUrl Not a pure module */
