// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function s(prim) {
  return prim;
}

function EditArticle(Props) {
  return React.createElement("div", {
              className: "editor-page"
            }, React.createElement("div", {
                  className: "container page"
                }, React.createElement("div", {
                      className: "row"
                    }, React.createElement("div", {
                          className: "col-md-10 offset-md-1 col-xs-12"
                        }, React.createElement("form", undefined, React.createElement("fieldset", undefined, React.createElement("fieldset", {
                                      className: "form-group"
                                    }, React.createElement("input", {
                                          className: "form-control form-control-lg",
                                          placeholder: "Article Title",
                                          type: "text"
                                        })), React.createElement("fieldset", {
                                      className: "form-group"
                                    }, React.createElement("input", {
                                          className: "form-control",
                                          placeholder: "What's this article about?",
                                          type: "text"
                                        })), React.createElement("fieldset", {
                                      className: "form-group"
                                    }, React.createElement("textarea", {
                                          className: "form-control",
                                          placeholder: "Write your article (in markdown)",
                                          rows: 8
                                        })), React.createElement("fieldset", {
                                      className: "form-group"
                                    }, React.createElement("input", {
                                          className: "form-control",
                                          placeholder: "Enter tags",
                                          type: "text"
                                        }), React.createElement("div", {
                                          className: "tag-list"
                                        })), React.createElement("button", {
                                      className: "btn btn-lg pull-xs-right btn-primary",
                                      type: "button"
                                    }, "Publish Article")))))));
}

var make = EditArticle;

exports.s = s;
exports.make = make;
/* react Not a pure module */
