// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Footer(Props) {
  return React.createElement("footer", undefined, React.createElement("div", {
                  className: "container"
                }, React.createElement("a", {
                      className: "logo-font",
                      href: "/"
                    }, "conduit"), React.createElement("span", {
                      className: "attribution"
                    }, "An interactive learning project from", React.createElement("a", {
                          href: "https://thinkster.io"
                        }, "Thinkster"), ". Code", "\u0026", "design licensed under MIT.")));
}

var make = Footer;

exports.make = make;
/* react Not a pure module */
