// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var ArticleData$ReactHooksTemplate = require("./ArticleData.bs.js");

function s(prim) {
  return prim;
}

function Home(Props) {
  var match = React.useReducer((function (_state, action) {
          return /* record */[/* articleList */action[0]];
        }), /* record */[/* articleList */undefined]);
  var dispatch = match[1];
  React.useEffect((function () {
          ArticleData$ReactHooksTemplate.fetchArticles((function (data) {
                  return Curry._1(dispatch, /* Loaded */[data]);
                }));
          return undefined;
        }));
  var renderArticleList = function (articleList) {
    if (articleList !== undefined) {
      return React.createElement("div", undefined, Belt_Array.map(articleList, (function (article) {
                        var article$1 = article;
                        return React.createElement("div", {
                                    key: article$1[/* slug */0],
                                    className: "article-preview"
                                  }, React.createElement("div", {
                                        className: "article-meta"
                                      }, React.createElement("a", {
                                            href: "profile.html"
                                          }, React.createElement("img", {
                                                src: article$1[/* author */9][/* image */2]
                                              })), React.createElement("div", {
                                            className: "info"
                                          }, React.createElement("a", {
                                                className: "author",
                                                href: ""
                                              }, article$1[/* author */9][/* username */0]), React.createElement("span", {
                                                className: "date"
                                              }, article$1[/* updatedAt */6])), React.createElement("button", {
                                            className: "btn btn-outline-primary btn-sm pull-xs-right"
                                          }, React.createElement("i", {
                                                className: "ion-heart"
                                              }), String(article$1[/* favoritesCount */8]))), React.createElement("a", {
                                        className: "preview-link",
                                        href: ""
                                      }, React.createElement("h1", undefined, article$1[/* title */1]), React.createElement("p", undefined, article$1[/* description */2]), React.createElement("span", undefined, "Read more...")));
                      })));
    } else {
      return null;
    }
  };
  return React.createElement("div", {
              className: "home-page"
            }, React.createElement("div", {
                  className: "banner"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("h1", {
                          className: "logo-font"
                        }, "conduit"), React.createElement("p", undefined, "A place to share your knowledge."))), React.createElement("div", {
                  className: "container page"
                }, React.createElement("div", {
                      className: "row"
                    }, React.createElement("div", {
                          className: "col-md-9"
                        }, React.createElement("div", {
                              className: "feed-toggle"
                            }, React.createElement("ul", {
                                  className: "nav nav-pills outline-active"
                                }, React.createElement("li", {
                                      className: "nav-item"
                                    }, React.createElement("a", {
                                          className: "nav-link disabled",
                                          href: ""
                                        }, "Your Feed")), React.createElement("li", {
                                      className: "nav-item"
                                    }, React.createElement("a", {
                                          className: "nav-link active",
                                          href: ""
                                        }, "Global Feed")))), renderArticleList(match[0][/* articleList */0])), React.createElement("div", {
                          className: "col-md-3"
                        }, React.createElement("div", {
                              className: "sidebar"
                            }, React.createElement("p", undefined, "Popular Tags"), React.createElement("div", {
                                  className: "tag-list"
                                }, React.createElement("a", {
                                      className: "tag-pill tag-default",
                                      href: ""
                                    }, "programming"), React.createElement("a", {
                                      className: "tag-pill tag-default",
                                      href: ""
                                    }, "javascript"), React.createElement("a", {
                                      className: "tag-pill tag-default",
                                      href: ""
                                    }, "emberjs"), React.createElement("a", {
                                      className: "tag-pill tag-default",
                                      href: ""
                                    }, "angularjs"), React.createElement("a", {
                                      className: "tag-pill tag-default",
                                      href: ""
                                    }, "react"), React.createElement("a", {
                                      className: "tag-pill tag-default",
                                      href: ""
                                    }, "mean"), React.createElement("a", {
                                      className: "tag-pill tag-default",
                                      href: ""
                                    }, "node"), React.createElement("a", {
                                      className: "tag-pill tag-default",
                                      href: ""
                                    }, "rails")))))));
}

var make = Home;

exports.s = s;
exports.make = make;
/* react Not a pure module */
