// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Footer$ReactHooksTemplate = require("./Footer.bs.js");
var Header$ReactHooksTemplate = require("./Header.bs.js");
var Component1$ReactHooksTemplate = require("./Component1.bs.js");
var Component2$ReactHooksTemplate = require("./Component2.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Header$ReactHooksTemplate.make, { }), "header");

ReactDOMRe.renderToElementWithId(React.createElement(Component1$ReactHooksTemplate.make, {
          message: "Hello! Click this text."
        }), "index1");

ReactDOMRe.renderToElementWithId(React.createElement(Component2$ReactHooksTemplate.make, {
          greeting: "Hello!"
        }), "index2");

ReactDOMRe.renderToElementWithId(React.createElement(Footer$ReactHooksTemplate.make, { }), "footer");

/*  Not a pure module */
