// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Home$ReactHooksTemplate = require("./Home.bs.js");
var Footer$ReactHooksTemplate = require("./Footer.bs.js");
var Header$ReactHooksTemplate = require("./Header.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Header$ReactHooksTemplate.make, { }), "header");

ReactDOMRe.renderToElementWithId(React.createElement(Home$ReactHooksTemplate.make, { }), "page");

ReactDOMRe.renderToElementWithId(React.createElement(Footer$ReactHooksTemplate.make, { }), "footer");

/*  Not a pure module */
