// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function s(prim) {
  return prim;
}

function Login(Props) {
  return React.createElement("div", {
              className: "auth-page"
            }, React.createElement("div", {
                  className: "container page"
                }, React.createElement("div", {
                      className: "row"
                    }, React.createElement("div", {
                          className: "col-md-6 offset-md-3 col-xs-12"
                        }, React.createElement("h1", {
                              className: "text-xs-center"
                            }, "Sign up"), React.createElement("p", {
                              className: "text-xs-center"
                            }, React.createElement("a", {
                                  href: ""
                                }, "Have an account?")), React.createElement("ul", {
                              className: "error-messages"
                            }, React.createElement("li", undefined, "That email is already taken")), React.createElement("form", undefined, React.createElement("fieldset", {
                                  className: "form-group"
                                }, React.createElement("input", {
                                      className: "form-control form-control-lg",
                                      placeholder: "Your Name",
                                      type: "text"
                                    })), React.createElement("fieldset", {
                                  className: "form-group"
                                }, React.createElement("input", {
                                      className: "form-control form-control-lg",
                                      placeholder: "Email",
                                      type: "text"
                                    })), React.createElement("fieldset", {
                                  className: "form-group"
                                }, React.createElement("input", {
                                      className: "form-control form-control-lg",
                                      placeholder: "Password",
                                      type: "password"
                                    })), React.createElement("button", {
                                  className: "btn btn-lg btn-primary pull-xs-right"
                                }, "Sign up"))))));
}

var make = Login;

exports.s = s;
exports.make = make;
/* react Not a pure module */
